[MODIFY] these models has been added to models.py {Student, Field, Te…
semjz/pyvengers-project pull request #45
Opened 2023-11-10 09:20 UTC by erfanmahram

…rm, Education, Enrollment}
لطفا یه چک میکنید، مخصوصا برای فیلد های ManyToMany چون ناآشنا بودم باهاشون خیلی ساختارش رو مطمئن نیستم، مثلا یه پارامتر داره به اسم thorough که نمیدونم اینجا نیاز بود استفاده شه یا نه.

2023-11-10 10:08 UTC, semjz commented
> …rm, Education, Enrollment} لطفا یه چک میکنید، مخصوصا برای فیلد های ManyToMany چون ناآشنا بودم باهاشون خیلی ساختارش رو مطمئن نیستم، مثلا یه پارامتر داره به اسم thorough که نمیدونم اینجا نیاز بود استفاده شه یا نه.

through زمانی استفاده می شد که یه تیبل میانی مثل enrollments خودمون تعریف کنیم بعد حالا بیایم به جنگو بگیم این رابطه چند به چند از این تیبیل استفاده می کنه وگرنه خودش برامون تیبل میانی رو میسازه

2023-11-10 10:13 UTC, semjz requested changes

2023-11-10 10:13 UTC, semjz commented on university/models.py
> +
فکر کنم یه فیلد courses باید اضافه کنی که many to many باشه و اونجا through=Enrollment باشه.                                                      courses = models.ManyToManyField(Course, through='Enrollment')

2023-11-10 10:45 UTC, erfanmahram commented on university/models.py
> +    course_condition = models.CharField(max_length=128, null=False, blank=False)
آها اوکی راس میگی درستش میکنم، گزینه هاش فقط پاس شده و نشده میشه؟ برای ثبت نام مثلا اخذ شده و در انتظار تایید و اینا نداره؟

2023-11-10 10:47 UTC, erfanmahram commented on university/models.py
> +    sanavat = models.IntegerField(null=False, blank=False)
سقف سنوات چقدره؟ بعد هر ترم از یه عددی که ماکزیمم هست باید کم بشه، و اونایی که سنوات تمدید میکنن چی میشه؟

2023-11-10 12:34 UTC, erfanmahram commented on university/models.py
> +    sanavat = models.IntegerField(null=False, blank=False)
یه مسئله دیگه ای هم هست، ما هیچ فیلدی مبنی بر ترم کنونی یا ترم فارغ التحصیلی دانشجو نداریم و اینکه این اختلاف رو بخوام در بیارم، اینجوری میشه که مثلا آخرین ترم ثبت شده تو سیستم رو منهای ترم ورودی دانشجو کنم... ولی اینجوری مشکلی که پیش میاد اینه که مثلا یکی که فارغ التحصیل شده هم به عنوان کسی که سنواتش تموم شده هی میبینیم. بهتر نیست یه فیلد فارغ التحصیلی هم برای دانشجو اضافه کنم؟

2023-11-10 13:17 UTC, erfanmahram commented on university/models.py
> +
ترمیک کورس باید باشه دیگه آره؟ چون درسای یه ترمو میخواد

2023-11-10 13:33 UTC, semjz commented on university/models.py
> +    sanavat = models.IntegerField(null=False, blank=False)
فعلا تمیدید نمی خواد همون سقف داشته باشه خوبه و اینم باید یه جا ذخیره کنیم که مثلا الان ترم مهر یا بهمن و کدوم سالیم که با توجه به سال و ترم ورودی دانشجو سنوات بدست بیاد

2023-11-10 13:34 UTC, semjz commented on university/models.py
> +    course_condition = models.CharField(max_length=128, null=False, blank=False)
نه تو این مرحله انتخاب واحد شده فقط مهمه درس پاس شده یا نه فکر کنم.

2023-11-10 14:35 UTC, erfanmahram commented
من تغییراتی ککه سامان گفته بود رو اعمال کردم. میشه لطفا دوباره بررسی کنید؟

@semjz @fatemejal

2023-11-11 18:02 UTC, semjz requested changes

2023-11-11 18:13 UTC, merged